-- AlterTable
ALTER TABLE "Listing" ADD COLUMN "ctaLabel" TEXT;
ALTER TABLE "Listing" ADD COLUMN "ctaUrl" TEXT;
ALTER TABLE "Listing" ADD COLUMN "phoneClicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "websiteClicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "instagramClicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "facebookClicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "ctaClicks" INTEGER NOT NULL DEFAULT 0;
